import os

import config


# Saved flowers and display size
SAVE_DIR = config.System.SAVE_DIR
WINDOW_WIDTH = 3840
WINDOW_HEIGHT = 2160
DISPLAY_SCALE = min(WINDOW_WIDTH / 1280, WINDOW_HEIGHT / 720)

# Flower count
MIN_FLOWERS = 10
MAX_FLOWERS = 30

# Ground area
GROUND_Y_MIN = int(WINDOW_HEIGHT * 0.55)
GROUND_Y_MAX = int(WINDOW_HEIGHT * 0.88)

# Flower size
FLOWER_SCALE_MIN = 0.12 * DISPLAY_SCALE
FLOWER_SCALE_MAX = 0.35 * DISPLAY_SCALE

# Bloom animation
BLOOM_DURATION_MIN = 1.2
BLOOM_DURATION_MAX = 2.4
BLOOM_STAGGER_MAX = 4.0

# Runtime
FOLDER_CHECK_INTERVAL = 2.0
FPS = 60

# Pig animation
PIG_IMAGE_PATH = os.path.join(config.BASE_DIR, "assets", "pig.png")
WALKPIG_ASSET_DIR = os.path.join(config.BASE_DIR, "assets", "walkpig")
PIG_ANIMATION_FPS = 6.0
PIG_SCALE_MIN = 0.33
PIG_SCALE_MAX = 0.63
PIG_SPEED_MIN = 30.0
PIG_SPEED_MAX = 70.0
PIG_WAIT_MIN = 0.6
PIG_WAIT_MAX = 2.0
PIG_JUMP_CHANCE = 0.24
PIG_JUMP_DURATION = 0.78
PIG_JUMP_HEIGHT = 95.0
PIG_SIT_CHANCE = 0.32
PIG_SIT_DURATION_MIN = 1.1
PIG_SIT_DURATION_MAX = 2.4
PIG_SPONTANEOUS_ACTION_MIN = 3.0
PIG_SPONTANEOUS_ACTION_MAX = 6.5
